minio:
  consoleIngress:
    hosts:
      - minio-console.kubrix.digiorg.cloud
    tls: 
      - secretName: minio-console-tls
        hosts:
          - minio-console.kubrix.digiorg.cloud
  ingress:
    hosts:
      - minio.kubrix.digiorg.cloud
    tls: 
      - secretName: minio-server-tls
        hosts:
          - minio.kubrix.digiorg.cloud
