backstage:
  ingress:
    host: backstage.kubrix.digiorg.cloud

  backstage:
    appConfig:
      app:
        baseUrl: https://backstage.kubrix.digiorg.cloud

      backend:
        baseUrl: https://backstage.kubrix.digiorg.cloud
        csp:
          frame-src: ['*.kubrix.digiorg.cloud']
        cors:
          origin: https://backstage.kubrix.digiorg.cloud

      proxy:
        endpoints:
          '/grafana/api':
            target: https://grafana.kubrix.digiorg.cloud

      argocd:
        baseUrl: https://argocd.kubrix.digiorg.cloud
        appLocatorMethods:
          - type: 'config'
            instances:
              - name: kubrix
                url: https://argocd.kubrix.digiorg.cloud
                token: ${ARGOCD_AUTH_TOKEN}

      auth:
        providers:
          oidc:
            development:
              callbackUrl: https://backstage.kubrix.digiorg.cloud/api/auth/oidc/handler/frame

      explore:
        tools:
          - title: Announcements
            description: Updates for your Employees
            url: /announcement
            image: /homepage/images/announcements.jpg
            tags:
              - Announcement
              - Employee
              - noHashtag
          - title: Central Monitoring
            description: Central Monitoring
            url: https://grafana.kubrix.digiorg.cloud/
            image: /homepage/images/monitoring.jpg
            tags:
              - Monitoring
              - Observability
          - title: GitOps CD
            description: Discover kubriX GitOps CD
            url: https://argocd.kubrix.digiorg.cloud/
            image: /homepage/images/platforms.jpg
            tags:
              - GitOps
              - CD
              - argocd
          - title: GitOps Promotion
            description: orchestrate stage-to-stage deployments
            url: https://kargo.kubrix.digiorg.cloud
            image: /homepage/images/sdk.jpg
            tags:
              - kargo
              - multistage
              - promotion
          - title: Thread Detection
            description: Discover security threats in real time
            url: https://falco.kubrix.digiorg.cloud
            image: /homepage/images/infrastructure.jpg
            tags:
              - falco
              - Threat Detection
              - Regulatory Compliance
          - title: IAM
            description: Identity and Access Management
            url: https://keycloak.kubrix.digiorg.cloud
            image: /homepage/images/hubs.jpg
            tags:
              - keycloak
              - sso
          - title: Secret Management
            description: Manage Secrets 
            url: https://vault.kubrix.digiorg.cloud
            image: /homepage/images/apps.jpg
            tags:
              - vault
              - secrets
      catalog:
        locations:
          - type: url
            target: https://github.com/hassavokado/kubrix/blob/main/backstage-resources/templates/showcase-templates-demo-stack.yaml
            rules:
              - allow: [Template]
          - type: url
            target: https://github.com/hassavokado/kubrix/blob/main/backstage-resources/entities/demo-stack.yaml

      grafana:
        domain: https://grafana.kubrix.digiorg.cloud

      kubecost:
        baseUrl: https://kubecost.kubrix.digiorg.cloud/
